#!/bin/bash -v

function testit {
    mono --debug xmrengtest.exe $1.lsl 2>&1 | tee $1.out
    diff $1.out $1.good
    mono --debug xmrengtest.exe -serialize $1.lsl 2>&1 | tee $1.ser
    diff $1.ser $1.good
}

function testev {
    mono --debug xmrengtest.exe -eventio $1.lsl < $1.events 2>&1 | tee $1.out
    diff $1.out $1.good
    mono --debug xmrengtest.exe -eventio -serialize $1.lsl < $1.events 2>&1 | tee $1.ser
    diff $1.ser $1.good
}

set -e
time make xmrengtest.exe
export MONO_PATH=../../../bin
export PATH=~/mono64.267/bin:$PATH

testit arraytest
testit chartest
testit objectest
testit proptest
testit trycatchexample
testit trycatchtest
testit while1
testev testllparcelmedia
testit typeassigntest
testit partialtest
testev statechange

mono --debug xmrengtest.exe -eventio -ipcchannel -2135482309 \
	-primname controller -primuuid 0000 ipctest0.lsl \
	-primname player1 -primuuid 1111 ipctest1.lsl << EOF | tee ipctest.out
1)touch_start(0)
"0000")llListRandomize:69827238
"1111")touch_start(0)
touch_start(0)
touch_start(0)
EOF
diff ipctest.out ipctest.good

mono --debug xmrengtest.exe -eventio -ipcchannel -2135482309 -serialize \
	-primname controller -primuuid 0000 ipctest0.lsl \
	-primname player1 -primuuid 1111 ipctest1.lsl << EOF | tee ipctest.ser
1)touch_start(0)
0)llListRandomize:69827238
1)touch_start(0)
touch_start(0)
touch_start(0)
EOF
diff ipctest.ser ipctest.gser

echo "SUCCESS"
